import './globals.css'
import EmotionRootStyleRegistry from './EmotionRootStyleRegistry';

export const metadata = {
  title: 'Mazadak',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <EmotionRootStyleRegistry>{children}</EmotionRootStyleRegistry>
      </body>
    </html>
  )
}
